jmxtrans.sh: reduce MaxTenuringThreshold to 15
This change allows jmxtrans to be used with jdk8
without causing any startup error like the following:

elukey@kafka-jumbo1001:/usr/share/jmxtrans$ ./jmxtrans.sh start
OpenJDK 64-Bit Server VM warning:
ignoring option PermSize=384m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=384m;
support was removed in 8.0
MaxTenuringThreshold of 16 is invalid; must be between 0 and 15
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

As far as I understand lowering the MaxTenuringThreshold for
jdk versions <= jdk 7 should not cause any harm, but please
let me know otherwise.

It would also be great to conditionally remove *PermSize
paramters from the cmdline for jdk >= 8 but since they are
ignored I'd skip this step.

Bug: T167992
Change-Id: I8bcc0b14942ba8eba73be6997bb603c9f3ef2699